format_version: 10
pipelines:
  backend:
    group: app-deployments
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-dabe9ad:
        git: https://github.com/SonnyMoney1/expense-shell.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - test-s:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            test-j:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - -l
                    command: ls
                    run_if: passed
